eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
    client:
        serviceUrl:
            defaultZone: http://localhost:7001/eureka/
kafka:
    producerConfig:
        metadata.broker.list: localhost:9092
        serializer.class: kafka.serializer.StringEncoder
    consumerConfig:
        zookeeper.connect: localhost:2181
        zookeeper.session.timeout.ms: 1000
        zookeeper.sync.time.ms: 1000
        auto.commit.interval.ms: 1000

zookeeper:
   connectionString: localhost:2181
   baseSleepTimeMs: 500
   maxRetries: 10
   
hls:
    hlsKey: key2
    rottenUrl: http://api.rottentomatoes.com/api/public/v1.0/movies/{rottenTomatoesProductId}/similar.json?apikey={apiKey}

hystrix:
    dashboard:
        serviceName: turbine-server
        clusterName: LibertasViPaaS


         
bookmark:
         databaseServiceName: http://database

creditcard:
    braintree:
         environment: sandbox
         merchantId: ddd44gynpmzcw45f
         publicKey: b4vn98989c7xs7dn
         privateKey: b197ffecb8077b6932fc3c69ef11f91a
    databaseServiceName: http://database
         

customer:
         databaseServiceName: http://database
         resetPasswordTopic: resetPasswordTopic
         updateCustomerTopic: updateCustomerTopic
         createCustomerTopic: createCustomerTopic
         deleteCustomerTopic: deleteCustomerTopic
         changePasswordTopic: changePasswordTopic

device:
         databaseServiceName: http://database

entitlement:
         databaseServiceName: http://database
         solrReadUrl: http://solrslave/solr/select

genre:
         databaseServiceName: http://database
ingestion:
        moduleRootFolder: D:/SharedVM/Workspaces/bitbucket/renaissance/ingestion/src/main/resources/routes
        activeModulesPattern: .*
        devicePresetMapping:
                H264 Smooth Streaming 720p: 16:9,HD,SMOOTH_HD,Wide_Screen
                H264 Smooth Streaming 720p for 3G or 4G: 16:9,HD,SMOOTH_HD,Wide_Screen
                H264 Broadband 720p: 16:9,HD,IPAD_HD,Wide_Screen
                H264 Smooth Streaming 1080p: 16:9,HD,SMOOTH_HD,Wide_Screen
                H264 Adaptive Bitrate MP4 Set 720p: 16:9,HD,SMOOTH_HD,Wide_Screen
                H264 Adaptive Bitrate MP4 Set SD 16x9: 16:9,HD,SMOOTH_HD,Wide_Screen
                H264 Adaptive Bitrate MP4 Set SD 4x3: 16:9,HD,SMOOTH_HD,Wide_Screen
                H264 Adaptive Bitrate MP4 Set 1080p for iOS Cellular Only: 16:9,HD,SMOOTH_HD,Wide_Screen
                H264 Smooth Streaming SD 4x3: 16:9,HLS,SMOOTH,Wide_Screen
                H264 Smooth Streaming SD 16x9: 16:9,HLS,SMOOTH,Wide_Screen
                VC1 Smooth Streaming 1080p: 16:9,HLS,SMOOTH,Wide_Screen
                H264 Adaptive Bitrate MP4 Set 1080p: 16:9,HLS,SMOOTH,Wide_Screen
        videoConfig:
                LibertasAzurePreviewOperation: ENCODE_PACKAGE
                CamelAzureEncryptorConfigPath: /media-encryptor.xml
                CamelAzurePackagerConfigPath: /media-packager-hls.xml
                CamelAzureURLSuffix: (format=m3u8-aapl) 
                LibertasAzureEncodePreset: H264 Smooth Streaming SD 4x3      
        metadataConfig:
                LibertasBindingRegex: .*/([a-zA-Z0-9-]*)_[a-zA-Z0-9\\\\.]*
                LibertasOverwriteList: false
                LibertasAPIKeyRegex: .*/([a-fA-F0-9-]*)/.*
                LibertasSearchableFields: title,id,directors,producers,genres,shorttitle,actors,producttype,releaseyear
                LibertasFileSystemHotfolder: /var/libertas/hotfolders
                LibertasFTPUsername: vienna
                LibertasS3LocalTempDirectory: C:/Temp/S3
                LibertasFTPPassword: man2than4
                LibertasFTPHotfolder: lemarkt.com:9031/ftp/dev
                LibertasPreviewEncodePresets: 
                LibertasImageTypeRegex: 
                LibertasS3ImageBucketName: libertasimages
                LibertasFTPLocalWorkingDirectory: C:/Users/pfenkam/localworkingdir
                LibertasCDNBaseURL: https://s3.amazonaws.com
                LibertasImageTypeDefault: Thumbnail
                CameAzureLocalTempDirectory: /var/libertas/azure
                libertasS3LocalTempDirectory: C:/Temp/s3
                libertasS3ImageBucketName: libertas
                libertasFileSystemHotfolder: C:/Temp/hotfolder
                libertasAPIKeyRegex: .*/([a-fA-F0-9-]*)/.*
                apiKey: 
                LibertasProductDB: ${libertas.database.prefix}LibertasProductDB
                LibertasSOLRSelectURL: http4://localhost:8983/solr/select
                LibertasSOLRUpdateURL: http4://localhost:8983/solr/update
        previewConfig:
                LibertasAzurePreviewOperation: ENCODE_PACKAGE
                CamelAzureEncryptorConfigPath: /media-encryptor.xml
                CamelAzurePackagerConfigPath: /media-packager-hls.xml
                CamelAzureURLSuffix: (format=m3u8-aapl) 
                LibertasAzureEncodePreset: H264 Smooth Streaming SD 4x3
                mediaServiceUri: https://media.windows.net/API/
                OAuthUri: https://wamsprodglobal001acs.accesscontrol.windows.net/v2/OAuth2-13
                scope: urn:WindowsAzureMediaServices
                encodePriority: 2
                policyDurationInMinute: 15
                clientId: fenkamlibertas1
                clientSecret: WHPM4Bn+ZlsZGY2i/kjBin5S4J87Ntpp0OGPl1bRLRI=
                LibertasS3EdgecastBucketName: aumedgecast
                LibertasS3EdgecastMP4BaseUrl: http://wpc.116d3.edgecastcdn.net/80116D3/aumedgecdn/
                LibertasS3EdgecastHLSBaseUrl: http://wpc.116d3.edgecastcdn.net/83116D3/aumedgecdn/
       
                
oauth2:
    publicKey: &publicKey -----BEGIN PUBLIC KEY-----MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGyCoGf0mH00M9BG0lYCS/WnlGcrBJkkjUKKYmR5CI+SUu5N+RAqC4lLFImRV4kGSiyFD8iv5sXZGnK+gVSq33dGI3DjW+RfmgKoUPKKPomSqnhJ/k+CSmGetfMLgOP4afIc7ucSEzqeLtAn3Ml6kmIAaRCvhnkj+ZHzjpxlW8GDAgMBAAE=-----END PUBLIC KEY-----
    privateKey: -----BEGIN RSA PRIVATE KEY-----MIICWwIBAAKBgGyCoGf0mH00M9BG0lYCS/WnlGcrBJkkjUKKYmR5CI+SUu5N+RAqC4lLFImRV4kGSiyFD8iv5sXZGnK+gVSq33dGI3DjW+RfmgKoUPKKPomSqnhJ/k+CSmGetfMLgOP4afIc7ucSEzqeLtAn3Ml6kmIAaRCvhnkj+ZHzjpxlW8GDAgMBAAECgYBFZpapZmtRSN4KzAEjOXzTtUbZZU4flJ00fcXIdRDgormf6QbvK7UNLpQIGIlf/kHaj5A0zyxORjkAQo/9UvxxOrqpJ8l9tayg4jg61adPZa0xegL/btIyfKl+tf6snljmgYhtHiGFsV8cK8Pd1oc9eS6kODPGYPKCpSXtuRg/QQJBALaDlSqKY7kNlJrJvjGX1BRy/TioOFbrlQGlqQAsJETS/jdei3uILx3SzqMWBR0ZVVYhHjruPcNmBZZ5oLyrF/kCQQCYMzH3+kqLLEIvFoDZVZh24lkXOJIKToujH1FBEXQDAG946BftIXXZ48cEIPn/lR6LknMPoFOuNXi5X9GGAxxbAkAYFuH3TXDAGgTFMV+DGDELyemWMs3M2yc9omnd9fWLh/W5xSbP1TeyzgIsEFn4b0GOLqzYxl0sjyippcALZuGxAkEAhuj6ZgEqimrUz8B2vi8tUlQY/Ihci15MUG+2KqM53l9IcDfq3XtHZ7iL9JD2iSK5TKan7zYCdu1W8ZqJsuyW+QJAZiO5LnmMKd+kbXvy0GKVujLF5pH57l3OiT09FK0Q4p+DtRpXhDpTC0NLHyplUuzPPgnanSqYzaOVUGaDWDYKUw==-----END RSA PRIVATE KEY-----
    clientId: libertas
    secret: ununsed_secret
    resources: 
          - resource
    scopes: 
          - read
          - write
    grantTypes: 
          - password
    client:
       tokenUri: http://oauth/uaa/oauth/token
       authorizationUri: http://oauth/uaa/oauth/authorize
       clientId: acme
       clientSecret: acmesecret
    resource:
       jwt:
           keyValue: *publicKey
    id: openid
    serviceId: ${PREFIX:}resource
    
offer:
         databaseServiceName: http://database
         
notification:
        velocityTemplates:
                createCustomerNotificationTemplate: Hi \$firstName,$newline Your account has been created. Thanks for choosing \$serviceName.$newline Your \$serviceName Team.
                updateCustomerNotificationTemplate: Hi \$firstName,$newline Your account has been updated. Thanks for choosing \$serviceName.$newline Your \$serviceName Team.
                deleteCustomerNotificationTemplate: Hi \$firstName,$newline Your account has been deleted. We are sorry to see you leave and hope to see you soon again.$newline Your \$serviceName Team.
                changePasswordNotificationTemplate: Hi \$firstName,$newline Your password has been changed. Thanks for choosing \$serviceName.$newline Your \$serviceName Team.
                resetPasswordNotificationTemplate: Hi \$firstName,$newline Your password has been reset to {newPassword}. Thanks for choosing \$serviceName.$newline Your \$serviceName Team.
                purchaseNotificationTemplate: 
                createTenantNotificationTemplate: Hi \$firstName,$newline Your tenant account has been created. Thanks for choosing \$serviceName.$newline Your \$serviceName Team.
                updateTenantNotificationTemplate: Hi \$firstName,$newline Your tenant account has been updated. Thanks for choosing \$serviceName.$newline Your \$serviceName Team.
                deleteTenantNotificationTemplate: Hi \$firstName,$newline Your tenant account has been deleted. We are sorry to see you leave and hope to see you soon again.$newline Your \$serviceName Team.
                addAdministratorNotificationTemplate: Hi \$firstName,$newline User with email {adminEmail} has been added as administrator of your tenant, {tenantName}. Thanks for choosing \$serviceName.$newline Your Libertas Team.
                removeAdministratorNotificationTemplate: Hi \$firstName,$newline User with email {adminEmail} has been removed as administrator of your tenant, {tenantName}. Thanks for choosing \$serviceName.$newline Your Libertas Team.
                createCustomerNotificationSubject: \$serviceName Account Created
                updateCustomerNotificationSubject: \$serviceName Account Updated
                deleteCustomerNotificationSubject: \$serviceName Account Deleted
                changePasswordNotificationSubject: \$serviceName Password Changed
                resetPasswordNotificationSubject: \$serviceName Password Reset
                purchaseNotificationSubject: \$serviceName Invoice
                createTenantNotificationSubject: \$serviceName Tenant Created
                updateTenantNotificationSubject: \$serviceName Tenant Configuration Updated
                deleteTenantNotificationSubject: \$serviceName Tenant Deleted
                addAdministratorNotificationSubject: \$serviceName Tenant Administrator Added
                removeAdministratorNotificationSubject: \$serviceName Tenant Administrator Removed
        databaseServiceName: http://database
        smtpProperties:
                mail.smtp.auth: true
                mail.smtp.starttls.enable: true
                mail.smtp.host: smtp.gmail.com
                mail.smtp.port: 587
                mail.from: pascal@fenkam.name
                mail.username: pascal@fenkam.name
                mail.password: solo77ville/.
         
playback:
         databaseServiceName: http://database
         playbackResponseTimoutMillis: 200
         playbackResponseMinCount: 1
         playbackLocationRequestTopic: playback-location-request2
         playbackLocationResponseTopic: playback-location-response2
         SolrReadUrl: http://solrslave/solr/select
         playbackLocationFrequencyMillis: 10000
         entitlementServiceUrlTemplate: http://entitlement/internal/v1/entitlement/check/product/{productId}?apiKey={tenantId}&customerId={customerId}
         deviceSpecMapping:
             mobile.*: .*

product:
         solrReadUrl: http://solrslave/solr/select
         solrWriteUrl: http://solrmaster/solr/update
         defaultSearcheableFields: title,id,directors,producers,genres,shorttitle,actors,producttype,releaseyear
         defaultQueryTemplate: title:{}  OR directors:{} OR shorttitle:{} OR producers:{} 
         databaseServiceName: http://database
         tenantServiceName: http://tenant
         offerServiceName: http://offer
         createProductLockPath: /catalog/product/lock/create
         createProductLockTimeoutMillis: 10000
         progressWatchedQueryTemplate: http://playback/internal/v1/playback/location/product/{productId}?customerId={customerId}&apiKey={tenantId}
         canWatchNowQueryTemplate: http://entitlement/internal/v1/entitlement/check/product/{productId}?customerId={customerId}&apiKey={tenantId}

   

promotion:
         databaseServiceName: http://database
         
         
         
purchase:
         solrReadUrl: http://solrslave/solr/select
         databaseServiceName: http://database
         tenantServiceName: http://tenant
         offerServiceName: http://offer
         purchaseTopic: purchaseTopic
         entitlementCreationUrlTemplate: http://entitlement/internal/v1/admin/entitlement/product/{productId}/offer/{offerId}?apiKey={tenantId}
         braintree: 
                environment: sandbox
                merchantId: ddd44gynpmzcw45f
                publicKey: b4vn98989c7xs7dn
                privateKey: b197ffecb8077b6932fc3c69ef11f91a
         
rating:
         databaseServiceName: http://database
         avgUserRatingComputationFrequencyMilis: 600000
         updateProductPath: /v1/product
         productServiceName: product
         avgUserRatingKafkaGroupId: rating.avg-user-rating.id
         ratingCreationTopic: createRating
         
review:
         databaseServiceName: http://database

recommendation:
        solrReadUrl: http://solrslave/solr/select
        databaseServiceName: http://database
        
rottentomatoesenrich:
        solrReadUrl: http://solrslave/solr/select
        solrWriteUrl: http://solrmaster/solr/update?commit=true
        databaseServiceName: http://database
        searchQueryUrlTemplate: http://api.rottentomatoes.com/api/public/v1.0/movies.json?apikey={apiKey}&q={searchTerm}&page_limit=1
        applicationKey: nwwhgh8hhtfvu77u85s25nc8
        solrSchemaChangeUrl: http://localhost:8983/solr/schema/fields
        quickPlaySourceUrl: http://54.191.76.80:8700/catalog-api/titles?type=movie&pageSize={pageSize}&pageNumber={pageNumber}
        
rottentomatoes:
        applicationName: LibertasQP
        applicationKey: nwwhgh8hhtfvu77u85s25nc8
        databaseServiceName: http://database
        solrReadUrl: http://solrslave/solr/select
        searchQueryUrlTemplate: http://api.rottentomatoes.com/api/public/v1.0/movies.json?apikey={apiKey}&q={searchTerm}&page_limit=5
        similarQueryUrlTemplate: http://api.rottentomatoes.com/api/public/v1.0/movies/{rottenTomatoesProductId}/similar.json?apikey={apiKey}
        rottenTomatoesIdField: rottenTomatoesId
        manualRecommendationFallbackEnabled: false
        
tenant:
         databaseServiceName: http://database
         createCustomerUrlTemplate: http://customer/v1/customer
         createTenantTopic: createTenantTopic
         updateTenantTopic: updateTenantTopic
         addAdministratorTopic: addAdministratorTopic
         removeAdministratorTopic: removeAdministratorTopic
         deleteTenantTopic: deleteTenantTopic
    
watchhistory:
         databaseServiceName: http://database
         
         
workflow:
         databaseServiceName: http://database

endpoints:
  autoconfig:
    id: autoconfig
    sensitive: false
    enabled: true
  beans:
    id: beans
    sensitive: false
    enabled: true
  env:
    id: env
    sensitive: false
    enabled: true
  metrics:
    id: metrics
    sensitive: false
    enabled: true
  extendedmetrics:
    id: extendedmetrics
    sensitive: false
    enabled: true
  trace:
    id: trace
    sensitive: false
    enabled: true
  dump:
    id: dump
    sensitive: false
    enabled: true
  configprops:
    id: configprops
    sensitive: false
    enabled: true
    keys-to-sanitize: password,secret
  health:
    id: health
    sensitive: false
    enabled: true
  info:
    id: info
    sensitive: false
    enabled: true
  jolokia:
    sensitive: false
    enabled: true
  error:
    path: /error
  refresh:
    id: refresh
    sensitive: false
    enabled: true  
  
